apiVersion: v1
kind: Namespace
metadata:
  name: template-analysis
  labels:
    app.kubernetes.io/name: template-analysis
    app.kubernetes.io/part-of: data-science-platform
    environment: development
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: template-analysis-quota
  namespace: template-analysis
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "5"
    secrets: "10"
    configmaps: "10"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: template-analysis-netpol
  namespace: template-analysis
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: template-analysis
    - namespaceSelector:
        matchLabels:
          name: monitoring
  egress:
  - {} # Allow all egress traffic
