[defaults]
template_path = "template"
output_path = "./.ctt/test-defaults"
answers_file = "ctt-answers.yml"
cleanup = true

[[test]]
name = "default"
answers = { short_name = "demo", author = "Test User" }
